[package]

name = "doppler"
version = "1.1.1"
authors = ["Andres Vahter <andres.vahter@gmail.com>"]

[dependencies]
clap = "*"
libc = "*"
time = "*"
num = "*"

[dependencies.gpredict]
git = "https://github.com/cubehub/rust-gpredict.git"
